# Generated by Django 6.0.7 on 2026-07-28 11:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, help_text='Internal length in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('width', models.DecimalField(decimal_places=2, help_text='Internal width in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Internal height in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of the box', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='box_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box_app.product')),
            ],
        ),
    ]
